trigger:
- master  # Defina a branch que deve acionar a pipeline

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    pip install -r requirements.txt
    python manage.py test
  displayName: 'Run Unit Tests'
